### ISSUE TITLE
Add in benchmarking option for FE/BE/ML

### ISSUE THREAD

**Issue by FernandoDavis** [INSO-4151-S22/BenchML#60]
- [x] Add in option to choose between optimization and adversarial evaluation when submitting a model @carolinasantia2 
- [x] Get the benchmarking type from backend when doing get on the models to display properly in model view @gabrosa7  , @FernandoDavis 
- [x] Create modularized sections for ML code to allow for ease of call between optimization and adversarial modules. @FernandoDavis 
- [x] Add adversarial evaluation on the backend when creating a model @gabrosa7

**Comment by carolinasantia2** [comment]
<img width="1146" alt="Screen Shot 2022-05-11 at 3 37 14 AM" src="https://user-images.githubusercontent.com/36648152/167794732-9140add8-dfc3-4a8d-a94d-4734c184bb93.png">
